### PR TITLE
Add docs for debugging in VS Code

### PR DESCRIPTION
**Pull request by katelynsills**
This PR adds a doc for debugging in VS Code.

### CODE REVIEW

**Comment by warner** [comment]
Does this depend upon the joi/minimist changes in #20 or was that incidental?

**Comment by katelynsills** [comment]
> Does this depend upon the joi/minimist changes in #20 or was that incidental?

It was dependent on that, but I just pushed up a version that should work 100% with only what is currently on master.

**Comment by katelynsills** [comment]
Awesome, thanks!!

**Comment by warner** [comment]
Huh, not sure why github didn't automatically close this one.

**Comment by warner** [comment]
Huh, I have no idea what unmerged commits it's talking about, it seems like ..

oh, the PR says "merge 2 commits into `minimist` from `debugging`", rather than merging into `master`. Looks like the PR got created a bit funny.

**Comment by katelynsills** [comment]
Ah, sorry, I did that intentionally to remind myself it was building on the minimist branch, and then forgot to change that when we decided to merge the debugging branch in separately.

**Pull request closed without merging**
