### PR TITLE
ertp demo: toward static types with flow (WIP)

### PR DESCRIPTION
**Pull request by dckc**
With respect to the goal of helping "non expert" devs write correct contracts: I'm struggling to read the ertp (contractHost) demo code.

In one of my own projects, when asking another dev to take on maintenance, I realized asking him to read the code without type annotations was a form of torture. :)

So I'm working on adding types. I'm most experienced / comfortable with flow, so I'm using that. I expect you're more likely to use typescript (or just JSDoc) if you ever do this sort of thing, so this PR is more of an FYI than an actual request to pull.

The issuers.chainmail file was quite the rosetta stone. (duh)

## `?Amount` and other "guards"

code such as:

```js
mustBeComparable(label);
```

doesn't work well with flow; I doubt it works well with typescript either. These tools work better with:

```js
const label = mustBeComparable(label);
```

or, to avoid shadowing:

```js
const label = mustBeComparable(labelArg);
```

## magic E, makePromise?

How do these come into scope?

Where is E defined? (I found `src/kernel/makePromise.js`)

### CODE REVIEW

**Comment by warner** [comment]
Yay! Thank you for diving into that, more/new eyeballs on this will definitely help a lot.

Yeah, `makePromise.js` is just a little utility I put together because (coming from Twisted and Deferreds) I can never remember how you get all three of (Promise, resolver, rejector). I appreciate why the JS syntax is the way it is, but it's going to take a while for it to feel natural to me, hence the utility.

`E` is created when we build the vat, as part of the interface with the "live slots" persistence layer. Take a look at the `setup` function in any of the vats: they're passing a `build()` callback into `makeLiveSlots()`, and that callback is invoked with the magic `E` wrapper function.

(`E` needs access to the internal liveslots tables which map from presences to the import index, and to the `syscall` function to actually send the serialized messages, which is why it can't be constructed until liveSlots is mostly constructed, so giving E to the callback seemed like the cleanest way to manage the interleaved build process)

**Comment by dckc** [comment]
I should probably make real PRs for these:

 - 4c48d34 null cannot be pass-by-presence, can it?
 - 0f733c4 marshal: why coerce to string and then check for string?

**Comment by erights** [comment]
Please do make separate PRs as you suggest at https://github.com/Agoric/SwingSet/pull/65#issuecomment-498112381

**Comment by dckc** [comment]
migrated to https://github.com/Agoric/ERTP/pull/12

**Pull request closed without merging**
