### PR TITLE
null cannot be pass-by-presence, can it?

### PR DESCRIPTION
**Pull request by dckc**

### CODE REVIEW

**Comment by dckc** [comment]
I suppose I owe a test case...

**Comment by erights** [comment]
Good catch on the missing null. Yes, a test case and then I'm ready to accept and merge. Thanks.

**Comment by dckc** [comment]
You can thank flow for catching the missing null :)

**Comment by warner** [comment]
@dckc thanks! If you wouldn't mind rebasing this to current trunk (in particular to a commit after the 0.0.11 release I made last night), I'd appreciate it, it'll make our commit history easier to follow. I'll land once that's done and there's a test case.

**Comment by dckc** [comment]
@warner I rebased and added a test.

**Pull request merged**
