### PR TITLE
marshal: why coerce to string and then check for string?

### PR DESCRIPTION
**Pull request by dckc**

### CODE REVIEW

**Comment by dckc** [comment]
I suppose I owe a test case...

**Comment by erights** [comment]
Yes, a test case and then I'm ready to accept and merge. Thanks.

**Comment by warner** [comment]
As with #67, please rebase to current trunk before we land this (sorry for the collsions, not your fault at all, I've been spinning new releases of SwingSet fairly quickly to support the cosmic-swingset work, increasing the churn).

**Comment by dckc** [comment]
@warner I rebased and added a test.

**Pull request closed without merging**
