### PR TITLE
Make command line args more flexible with better error messaging

### PR DESCRIPTION
**Pull request by katelynsills**
This PR adds `minimist` and `Joi`. `minimist` parses command line arguments and gives an object. So, `$ bin/vat  run demo/contractHost --mint --no-ses` turns into

```
{ _: [ 'run', 'demo/contractHost' ],
  mint: true,
  ses: false }
```
This allows us to be flexible about the ordering of the options. Without this, adding --no-ses to the end (as a new user will probably do) will fail silently.

This PR also adds a Joi schema that allows us to specify exactly what we want to allow as command line arguments. For instance, which options can be used in conjunction with each other? Which arguments are optional and which are required? What are their types? Anything that doesn't match what we expect causes an error with an exact message.

For instance, if we do `$ bin/vat --inspect-brk=7603 run demo/contractHost --mint --hi`, we get back:
`"hi" is not allowed`.

If we do `$ bin/vat --inspect-brk=7603 run demo/contractHost --mint --trivial` we get:
`"mint" conflict with forbidden peer "trivial"`

The error messages could probably use some rewording.

### CODE REVIEW

**Comment by warner** [comment]
I definitely like the idea of a schema for the arguments and improving the learning process for likely mistakes. I'm nervous about 1: allowing too much flexibility (in particular making it hard to tell whether a given argument might be for the bootstrap vat to interpret, or for the vat-runner), and 2: adding more code into our TCB. We might deal with the latter by running Joi/minimist inside SES, if possible.

For the first.. what does this patch do with the `--no-ses` -at-the-end case? does it throw an error or accept it as a vat-runner argument?

**Comment by katelynsills** [comment]
Ah, gotcha. Do you think our audience will be able to recognize that we are using the placement and ordering of the options to make a distinction between arguments for the vat-runner and arguments for the bootstrap vat? It looks like both `minimist` and `yargs` for the most part disregard the order of options and turn all of them into keys and values of a top-level object, so it seems to be common practice to assume that the order of the options shouldn't matter. 

Screen Shot 2019-04-16 at 11 18 02 AM

Screen Shot 2019-04-16 at 11 11 56 AM

Do you think the distinction between arguments for the vat-runner and arguments for the bootstrap vat is important enough to break (what I assume to be) common assumptions? I was thinking that we could look at it as if all arguments go to the vat-runner, since they do, and the vat-runner selects a subset of those to pass on to the bootstrap vat. I think that still retains clarity while also matching our user's expectations. 

> For the first.. what does this patch do with the `--no-ses` -at-the-end case? does it throw an error or accept it as a vat-runner argument?

Right now it accepts it as a vat-runner argument.

**Comment by warner** [comment]
Hm. Most of the command-line tools I've used that know about "subcommands" do seem to care about ordering (e.g. `git --git-dir=.git status` is ok, `git status --git-dir=.git` is not). I think `yargs` does this when you use the `.command()` method (although I'll admit I haven't tested it), but I know of popular Python and Rust libraries that certainly do the same. And there's an old unix convention of `--` to separate arguments when the first executable is being used to run some other executable, e.g. in tools like Rust's `cargo run`: `cargo run --jobs 4 -- PROGRAM-ARGS` tells `cargo` to compile the program with four parallel jobs, then run the compiled result with `PROGRAM-ARGS`. So I guess I'm leaning towards sticking with a hierarchical/scoped argument layout: `COMMAND --command-args SUBCOMMAND --subcommand-args -- target-args`.

Also, I don't think `bin/vat` should know about the contents of `demo/` or the arguments that the various demos inside it might take. I might be reading the patch wrong, but it looks like `bin/vat demo/otherdemo --otherarg` would be rejected because `--otherarg` isn't something that `demo/contractHost` takes. And if `bin/vat` should enforce arguments based on the actual vat basedir being loaded, we'd need to put that schema into the basedir somewhere (e.g. maybe `DIR/bootstrap.js` should import `joi` or `minimist` and check its own arguments, rejecting unknown ones to catch the `--no-ses`-at-the-end case, except that until we get the module loader it isn't so easy to do that import).

**Comment by katelynsills** [comment]
That all makes sense to me. I'll go ahead and close this in favor of a future PR that better fits these requirements. Thanks for explaining!

**Pull request closed without merging**
